### ISSUE TITLE
AttributeError: 'SimpleUniversalBuffer' object has no attribute 'get_batch_generator'

### ISSUE THREAD

**Issue by Jackson12826** [jiangsy/mbpo_pytorch#1]
I got this error report when I run "run_mbpo.py",and I actually didn't see this methed in class SimpleUniversalBuffer,there are only get_batch_generator_inf and get_batch_generator_epoch in this class,please tell me what should I do.

**Comment by jiangsy** [comment]
I made a quick fix. 
Sorry for the problem. I updated some code using my personal codebase and forgot to check the consistency. I would recommend you to check the implementation yourself. I would run some benchmarking tests later since I am a little bit busy these days.

**Comment by Jackson12826** [comment]
thanks!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiangsy/mbpo_pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月24日(星期四) 下午4:56
收件人:&nbsp;"jiangsy/mbpo_pytorch"<mbpo_pytorch@noreply.github.com&gt;;
抄送:&nbsp;"旺仔"<694780346@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jiangsy/mbpo_pytorch] AttributeError: 'SimpleUniversalBuffer' object has no attribute 'get_batch_generator' (#1)





 
I made a quick fix.
 Sorry for the problem. I updated some code using my personal codebase and forgot to check the consistency. I would recommend you to check the implementation yourself. I would run some benchmarking tests later since I am a little bit busy these days.

**Comment by Jackson12826** [comment]
> I made a quick fix.
> Sorry for the problem. I updated some code using my personal codebase and forgot to check the consistency. I would recommend you to check the implementation yourself. I would run some benchmarking tests later since I am a little bit busy these days.

thanks!
