### ISSUE TITLE
unable to find priv.yaml

### ISSUE THREAD

**Issue by DesikRengarajan** [jiangsy/mbpo_pytorch#2]
Hi, 
Firstly, thank you very much for a PyTorch implementation of MBPO. While I was going over your code, I noticed that you are using priv.yaml in run_mbpo.py, but I was unable to find this file in the config folder, apologies in advance if I have missed it. 

Thanks, 
Desik

**Comment by jiangsy** [comment]
sorry it's the config that defines the proj_dir and some other private configs used in the project. You can create it yourself and add something you need, or you can just change the proj_dir in mbpo.yaml.

**Comment by DesikRengarajan** [comment]
Thank you!
