### ISSUE TITLE
Rewards in Hopper Benchmarking Environments 

### ISSUE THREAD

**Issue by DesikRengarajan** [jiangsy/mbpo_pytorch#3]
Hi, 
I was going over the step function in hopper.py and noticed that the reward function used here is slightly different from the original one present in OpenAI gym, may I know the reason behind using a modified reward function? 

Thanks, 
Desik

**Comment by jiangsy** [comment]
You can check OriginalHopperEnv in gym_ohopper.py. I think it's the same as the Hopper-v2.
