### ISSUE TITLE
Could you show some results of using this repo on mujoco?

### ISSUE THREAD

**Issue by jiaruonan** [jiangsy/mbpo_pytorch#5]

**Comment by x35f** [comment]
Hi, the original owner of this repo has graduated and this repo is no longer maintained. Here(https://github.com/x35f/model_based_rl) is a new MBPO Pytorch re-implementation that strictly follows the original TF version. We have tested it in the Hopper and Walker2d task. In Hopper, it takes 4.5 hours to the 75k convergent step with reward \approx 3100. In Walker2d, it takes 1 day and 2 hours to the 300k convergent step with reward \approx 4500. Both of them are run on a machine with CPU 12900kf and RTX 3080. We are currently running more experiments on MuJoCo. Feel free to contact me through xufeng@lamda.nju.edu.cn for further questions.

**Comment by jiaruonan** [comment]
> Hi, the original owner of this repo has graduated and this repo is no longer maintained. Here(https://github.com/x35f/model_based_rl) is a new MBPO Pytorch re-implementation that strictly follows the original TF version. We have tested it in the Hopper and Walker2d task. In Hopper, it takes 4.5 hours to the 75k convergent step with reward \approx 3100. In Walker2d, it takes 1 day and 2 hours to the 300k convergent step with reward \approx 4500. Both of them are run on a machine with CPU 12900kf and RTX 3080. We are currently running more experiments on MuJoCo. Feel free to contact me through [xufeng@lamda.nju.edu.cn](mailto:xufeng@lamda.nju.edu.cn) for further questions.

ok, thanks for your reply!
