### ISSUE TITLE
May I ask how long it takes to run it once? I only ran it 137 times in a whole day

### ISSUE THREAD

**Issue by sltju** [jiangsy/mbpo_pytorch#6]
May I ask how long it takes to run `python ./mbpo_pytorch/scripts/run_mbpo.py`  once? I only ran it 137/1000 epochs in a whole day.

**Comment by x35f** [comment]
Hi, the original owner of this repo has graduated and this repo is no longer maintained. Here(https://github.com/x35f/model_based_rl) is a new MBPO Pytorch re-implementation that strictly follows the original TF version. We have tested it in the Hopper and Walker2d task. In Hopper, it takes 4.5 hours to the 75k convergent step with reward \approx 3100. In Walker2d, it takes 1 day and 2 hours to the 300k convergent step with reward \approx 4500. Both of them are run on a machine with CPU 12900kf and RTX 3080. We are currently running more experiments on MuJoCo. Feel free to contact me through xufeng@lamda.nju.edu.cn for further questions.

**Comment by sltju** [comment]
Thank you for your work！！！
